name: Build a LinuxDwarfPack AppImage with all dependencies

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        # lnp-forge build dependencies
        source scripts/build/debian.sh
        sudo apt-get install $(get_debian_build_dependencies) apt-rdepends
        # install appimagetool AppImage
        sudo apt install -y python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse
        sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
        sudo chmod +x /usr/local/bin/appimagetool
        sudo pip3 install appimage-builder

    - name: Name package
      id: slug
      run: |
        echo "PKG_NAME=LinuxDwarfPack-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "DIR_NAME=LinuxDwarfPack-$(source version.sh)" >> $GITHUB_ENV

    - name: Build
      run: |
        echo "CT_LOG_PROGRESS_BAR=n" >> .config
        echo "CT_APPIMAGE=y" >> .config
        echo "CT_APPIMAGE_WITH_DEPENDENCIES=y" >> .config
        autoreconf && ./configure --prefix=$PWD && make install && bin/lnp-forge build

    # see https://appimage-builder.readthedocs.io/en/latest/intro/tutorial.html#script-step
    # for creating AppImage with deps
          
    - name: Upload build log
      uses: actions/upload-artifact@v2
      with:
        name: build.log
        path: |
            build.log
            AppImageBuilder.yml
      if: ${{ failure() }}

    - name: Upload AppImage
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PKG_NAME }}.AppImage
        path: Dwarf_Fortress-*-x86_64.AppImage
